// GENERATED by scripts/build-brand.mjs from brand.config.json — do not edit by hand.
// Change the colour in brand.config.json and run `npm run brand`.
//
// Prefer the CSS tokens (text-primary, bg-primary, text-wordmark …) in normal components.
// These literals exist for the few places that render OUTSIDE the stylesheet — currently
// only app/global-error.tsx, the root error boundary.

export const BRAND = {
  primary: "#E0473B",
  accent: "#C4643C",
  danger: "#B91C1C",
  wordmark: "#3B3838",
  btnInk: "#FFFFFF",
  surface: "#f6f8fb",
} as const;

export const BRAND_DARK = {
  primary: "#e97b72",
  accent: "#da9b81",
  danger: "#e34545",
  wordmark: "#ece9e9",
  btnInk: "#02060F",
} as const;
