// Fan brand.config.json out to every WEB consumer of the brand colours.
// Run: npm run build:brand   (or `npm run brand` to do the icons too)
//
// Why a generator instead of just editing the CSS: the brand colour was previously typed
// into five unrelated files — globals.css, gen-icons.mjs, global-error.tsx, the Android
// colors.xml and the backend's email/FCM constants — and they had already drifted into
// three different "brand" hexes. One config in, every consumer out, no drift possible.
//
// Writes (all generated, all committed — same convention as build-legal.mjs / gen-icons.mjs):
//   app/brand.css              theme tokens, imported first by app/globals.css
//   lib/brand.generated.ts     literal hexes for TS that renders outside the CSS pipeline
//   public/manifest.json       theme_color / background_color only (icons left alone)
//   capacitor-www/index.html   the native shell's fallback loader
//
// The Android side is written by gen-icons.mjs, which reads the same config.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadBrand, tripleFromHex, ROOT } from "./brand-lib.mjs";

const brand = loadBrand();

// Mirrors --bg in app/globals.css (and THEME_COLOR in components/theme-toggle.tsx). The page
// surface is a neutral, not a brand colour, so it is deliberately NOT in brand.config.json —
// but the manifest and the native loader still need it as a literal.
const SURFACE_LIGHT = "#f6f8fb";

const BANNER = (what) =>
  `GENERATED by scripts/build-brand.mjs from brand.config.json — do not edit by hand.\n` +
  `Change the colour in brand.config.json and run \`npm run brand\`.${what ? "\n" + what : ""}`;

const write = (rel, body) => {
  writeFileSync(resolve(ROOT, rel), body);
  console.log("  wrote", rel);
};

// ---------------------------------------------------------------- app/brand.css
// Only the BRAND-owned tokens live here. The neutrals (--bg, --surface, --fg, …) and the
// categorical chart pair stay in globals.css: they are not brand-derived, and splitting them
// this way means regenerating can never clobber hand-written CSS.
//
// Values are space-separated RGB channels, not hex, because Tailwind's <alpha-value>
// placeholder needs channels to build `rgb(… / 0.2)` for opacity modifiers like bg-primary/20.
function brandCss() {
  const tokens = (t) =>
    [
      ["--primary", t.primary],
      ["--accent", t.accent],
      ["--danger", t.danger],
      ["--wordmark", t.wordmark],
      ["--btn-ink", t.btnInk],
    ]
      .map(([name, hex]) => `  ${name}: ${tripleFromHex(hex)}; /* ${hex.toUpperCase()} */`)
      .join("\n");

  return `/* ${BANNER("").split("\n").join("\n   ")} */

:root,
:root[data-theme="light"] {
${tokens(brand.light)}
}

/* Dark variants are DERIVED (see relight() in scripts/brand-lib.mjs), not hand-picked, so a
   new primary drags its dark counterpart along instead of leaving the two themes out of step. */
:root[data-theme="dark"] {
${tokens(brand.dark)}
}
`;
}

// ------------------------------------------------------- lib/brand.generated.ts
// app/global-error.tsx is a root error boundary: it renders when the app failed to boot, so
// the stylesheet may not be there and it must use inline literal hexes. This is the only
// reason literals are exported at all — prefer the CSS tokens everywhere else.
function brandTs() {
  return `// ${BANNER("").split("\n").join("\n// ")}
//
// Prefer the CSS tokens (text-primary, bg-primary, text-wordmark …) in normal components.
// These literals exist for the few places that render OUTSIDE the stylesheet — currently
// only app/global-error.tsx, the root error boundary.

export const BRAND = {
  primary: "${brand.light.primary}",
  accent: "${brand.light.accent}",
  danger: "${brand.light.danger}",
  wordmark: "${brand.light.wordmark}",
  btnInk: "${brand.light.btnInk}",
  surface: "${SURFACE_LIGHT}",
} as const;

export const BRAND_DARK = {
  primary: "${brand.dark.primary}",
  accent: "${brand.dark.accent}",
  danger: "${brand.dark.danger}",
  wordmark: "${brand.dark.wordmark}",
  btnInk: "${brand.dark.btnInk}",
} as const;
`;
}

// ------------------------------------------------------------ public/manifest.json
// Read-modify-write, NOT a rewrite: the icons array, name, scope and display mode are
// hand-maintained and must survive. Only the two colour fields are ours.
function patchManifest() {
  const path = resolve(ROOT, "public/manifest.json");
  const manifest = JSON.parse(readFileSync(path, "utf8"));
  manifest.theme_color = SURFACE_LIGHT;
  manifest.background_color = SURFACE_LIGHT;
  writeFileSync(path, JSON.stringify(manifest, null, 2) + "\n");
  console.log("  wrote public/manifest.json (theme_color, background_color)");
}

// -------------------------------------------------------- capacitor-www/index.html
// The native shell's fallback loader. With capacitor.config.js `server.url` set, the live
// site loads over the top of this within a second — but on a cold or offline start this is
// the first thing a user sees, so it should not flash the old palette.
function loaderHtml() {
  return `<!doctype html>
<!-- ${BANNER("")} -->
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <title>Bari360</title>
    <style>
      html, body {
        margin: 0; height: 100%;
        background: ${SURFACE_LIGHT}; color: #64748b;
        font-family: system-ui, -apple-system, sans-serif;
        display: flex; align-items: center; justify-content: center;
      }
      .spinner {
        width: 40px; height: 40px; border-radius: 50%;
        border: 3px solid rgba(15, 23, 42, 0.12); border-top-color: ${brand.light.primary};
        animation: spin 0.8s linear infinite;
      }
      @keyframes spin { to { transform: rotate(360deg); } }
    </style>
  </head>
  <body>
    <!-- Fallback loader. With capacitor server.url set, the live site loads over this. -->
    <div class="spinner" aria-label="Loading Bari360"></div>
  </body>
</html>
`;
}

console.log("Brand:", brand.primary, "· ink", brand.ink);
write("app/brand.css", brandCss());
write("lib/brand.generated.ts", brandTs());
patchManifest();
write("capacitor-www/index.html", loaderHtml());
console.log("Done. Run `npm run gen-icons` for the images + Android resources.");
